### ISSUE TITLE
Errorji v kodi

### ISSUE THREAD

**Issue by oskarvavtar** [oskarvavtar/Skoraj-konstantne-vsote-trikotnih-funkcij-na-zaprtem-intervalu#3]
Pozdrav!
Nove težave v kodi (datoteka [`koda.ipynb`](https://github.com/oskarvavtar/Skoraj-konstantne-vsote-trikotnih-funkcij-na-zaprtem-intervalu/blob/main/Koda/koda.ipynb)). Pred tem bi samo vprašal naslednje: če imamo v kodi dve napaki iste sorte drugo poleg druge, ali bo Sage javil obe ali le prvo? Oba error-ja s katerima sva se srečala bodisi namigujeta na to bodisi sta še bolj čudna.

1. Prvi problem (v te kodi sicer ni viden): napako javi v vrstici 74, kjer nastaviva `a = 0`. Sam sem najprej posumil, da bi bilo treba v `def generiraj` zamenjati `range_x=(0, 1)` s `range_x=[0, 1]` (malo čudno, ker nad vrstico 75, `c = 1`, ni bilo pritožb). Ko sem stvar spremenil stvar ni prav nič napredovala. Namesto `def generiraj(range_x=[0, 1], range_y=[0, 100))`, kjer je bil error naslednji:
```
Error in lines 74-74
Traceback (most recent call last):
  File "/cocalc/lib/python3.9/site-packages/smc_sagews/sage_server.py", line 1230, in execute
    exec(
  File "", line 1, in <module>
  File "", line 6, in vsota_trikotnih_funkcij
```
 sem poskusi: 
* `def generiraj(range_x=[0, 1], range_y=(0, 100))`: error ostal isti
* `def generiraj(range_x=[0, 1], range_y=[0, 100])`: error ostal isti
* `def generiraj(range_x=[0, 1], range_y=[0, 100))`: error spremenil v 
```
Error in lines 34-40
Traceback (most recent call last):
  File "/cocalc/lib/python3.9/site-packages/smc_sagews/sage_server.py", line 1231, in execute
    compile(block + '\n',
  File "<string>", line 9
    def generiraj(range_x=[Integer(0), Integer(1)], range_y=[Integer(0), Integer(100))):
IndentationError: unexpected unindent
```
Sumim, da težava leži nekje drugje.

2. Napaka videna v te kodi:
```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-17-7176320d8943> in <module>
    111     return [vsota, (M, m)]
    112 
--> 113 vsota_trikotnih_funkcij(seznam_funkcij, seznam_tock)

<ipython-input-17-7176320d8943> in vsota_trikotnih_funkcij(seznam_funkcij, seznam_tock)
     99     p = MixedIntegerLinearProgram(maximization=True)
    100     v = p.new_variable(binary=True)
--> 101     p.set_objective(M-m)
    102     for i in enumerate(seznam_tock):
    103         p.add_constraint(sum(f(x(i)) * v[j] for j in range(Integer(1), n) <= M))

UnboundLocalError: local variable 'M' referenced before assignment
```
Zato tudi vprašanje na začetku, ker tu javi napako le za `M`, za `m` ne. Po čisti programerski logiki je jasno, da program ne more "delati" z nečim, kar še ni definirano, vendar se tu, ker gre za linearni program, vseeno zdi, da bi omemba v omejitvah (` p.add_constraint(sum(f(x(i)) * v[j] for j in range(1, n) <= M))`) morala zadostovati.

3. Reševanje problema minimiziranja: bi bila sprememba iz `True` v `False` pri `p = MixedIntegerLinearProgram(maximization=True)` zadostna, ali bi morala uporabiti morda kakšno drugo metodo oz. ukaz ali v končni fazi celo "na roko" obrniti program?

Lep pozdrav,
Oskar

**Comment by jaanos** [comment]
Pri prvi napaki težko rečem, kaj točno je narobe - izgleda, da se pri trenutni različici ta problem ne pojavi. Sicer pa je vseeno, če range pišeta z navadnimi ali oglatimi oklepaji (tukaj ne gre za odprte in zaprte intervale, pač pa za Pythonov par oziroma seznam - pri tej uporabi ni razlike), medtem ko je uporaba `[0, 100)` sintaktično nepravilna.

Pri drugi napaki gre za to, da spremenljivki `M` in `m` nista nikjer definirani (tako kot imata `v`). Pravzaprav bo najlažje, če namesto `M` in `m` pišeta `p['M']` in `p['m']` - tako dobljene spremenljivke so namreč privzeto realne.

Za minimizacijo, kot si rekel, uporabita `maximization=False`.

**Comment by nezakrzan** [comment]
Pozdravljeni,

še vedno imava težave pri spremenljivkah `M` in `m`.

Koda glede CLP izgleda sedaj takole:

`def vsota_trikotnih_funkcij(seznam_funkcij, seznam_tock):
    k = len(seznam_tock)
    n = len(seznam_funkcij)

    p = MixedIntegerLinearProgram(maximization=False)
    v = p.new_variable(binary=True)
    M = p.new_variable(integer=True)
    m = p.new_variable(integer=True)

    p.set_objective(M-m)
    for i in enumerate(seznam_tock):
        p.add_constraint(sum(f(x[i]) * v[j]for j in range(1, n) <= p['M'] ))
        p.add_constraint(sum(f(x[i]) * v[j] for j in range(1, n) >= p['m']))

    p.add_constraint(sum(v[j] for j in range(1,n) >= 1))
    p.add_constraint(sum(v[j] for j in range(1,n) <= z))

    vsota = p.solve()
    M, m = p.get_values(M), p.get_values(m)
    return [vsota, (M, m)]

vsota_trikotnih_funkcij(seznam_funkcij, seznam_tock)`

in error, ki ga vrne:
`TypeError: unsupported operand type(s) for -: 'sage.numerical.mip.MIPVariable' and 'sage.numerical.mip.MIPVariable'`

 Predvidevam, da spremenljivki še vedno nista prvilno zapisani. Nama lahko kako pomagate?

Hvala in lep pozdrav,
Neža

**Comment by oskarvavtar** [comment]
Sva prišla mimo tega errorja, so pa popravki pripeljali nov error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-8-089654e03536> in <module>
    117 
    118 
--> 119 vsota_trikotnih_funkcij(seznam_funkcij, seznam_tock)

<ipython-input-8-089654e03536> in vsota_trikotnih_funkcij(seznam_funkcij, seznam_tock)
    102     m = p.new_variable(integer=False, nonnegative=True)
    103     for i in seznam_tock:
--> 104         p.add_constraint(sum(seznam_funkcij[j](x[i]) * v[j] for j in range(Integer(1), n) <= M))
    105         p.add_constraint(sum(seznam_funkcij[j](x[i]) * v[j] for j in range(Integer(1), n) >= m))
    106     p.add_constraint(sum(v[j] for j in range(Integer(1),n) >= Integer(1)))

TypeError: '<=' not supported between instances of 'range' and 'sage.numerical.mip.MIPVariable'
```
Torej nama ne pusti zapisati pogojev 
![equation](https://latex.codecogs.com/gif.latex?%5Csum_%7Bj%3D1%7D%5Er%20f_j%28x_i%29v_j%20%5Cleq%20M)
![equation](https://latex.codecogs.com/gif.latex?%5Csum_%7Bj%3D1%7D%5Er%20f_j%28x_i%29v_j%20%5Cgeq%20m)
(mislim, da se enačbe dobro vidi le v "dnevnem načinu").

Trenutna koda linearnega programa je
```
def vsota_trikotnih_funkcij(seznam_funkcij, seznam_tock, z):
    k = len(seznam_tock)
    n = len(seznam_funkcij)

    p = MixedIntegerLinearProgram(maximization=False)
    v = p.new_variable(binary=True)
    M = p.new_variable(integer=False, nonnegative=True)
    m = p.new_variable(integer=False, nonnegative=True)
    for i in seznam_tock:
        p.add_constraint(sum(seznam_funkcij[j](x[i]) * v[j] for j in range(1, n) <= M))
        p.add_constraint(sum(seznam_funkcij[j](x[i]) * v[j] for j in range(1, n) >= m))
    p.add_constraint(sum(v[j] for j in range(1,n) >= 1))
    p.add_constraint(sum(v[j] for j in range(1,n) <= z))
    p.set_objective(M-m)

    vsota = p.solve()
    M, m = p.get_values(M), p.get_values(m)
    vkljucene = []
    for j in range(1,n):
        if v[j] == 1:
            vkljucene.append(seznam_funkcij[j])
    return [vsota, vkljucene]


vsota_trikotnih_funkcij(seznam_funkcij, seznam_tock, z)
```
Dostopna je v datoteki [`koda`](https://github.com/oskarvavtar/Skoraj-konstantne-vsote-trikotnih-funkcij-na-zaprtem-intervalu/blob/main/Koda/koda.ipynb), v isti [mapi](https://github.com/oskarvavtar/Skoraj-konstantne-vsote-trikotnih-funkcij-na-zaprtem-intervalu/tree/main/Koda) pa je še vedno prejšnja različica [`koda_0`](https://github.com/oskarvavtar/Skoraj-konstantne-vsote-trikotnih-funkcij-na-zaprtem-intervalu/blob/main/Koda/koda_0.ipynb), na katero se je nanašalo Nežino vprašanje (za vsak primer, če bi bila bolj pravilna kot trenutna).

LP,
Oskar

**Comment by jaanos** [comment]
Kolikor vidim, je težava v tem, da mora biti primerjava izven `sum`, torej med zadnjima zaklepajema. Enako velja za sledeča pogoja.

**Comment by nezakrzan** [comment]
Pozdravljeni,
mislim, da bi morala sedaj koda delati(nahaja se v mapi Koda in sicer v datoteki `koda_0.ipynb`), vendar ne razumem ravno zakaj mi sedaj vrača samo eno trikotno funkcijo, ki spada v izračun ciljne funkcije. Ali je to možno zato ker imam pogoja, da je vsota spremenljivk `v_j` med 1 in 7?

**Comment by jaanos** [comment]
Mislim, da je to bolj posledica tega, kako se generirajo funkcije - glede na to, da imajo vse pozitiven vrh, bo seveda najbolje izbrati čim manj funkcij. Navodila naloge tudi predvidevajo, da se omejita na določen interval, v katerem gledata vrednosti vsote funkcij (sicer bo minimum katerekoli vsote vedno 0). Točke bo torej potrebno vzeti samo v tem intervalu, npr.
```python
seznam_funkcij = [TrikotnaFunkcija.generiraj(range_x=(-2, 2), range_y=(0, 10)) for i in range(n)]
a, b = -1, 1 # gledamo vrednosti v intervalu [a, b]
seznam_tock = sorted(set(x for f in seznam_funkcij for x in f.prelomi if a <= x <= b).union({a, b}))
```
Če poženem na ta način, dobim včasih tudi več funkcij v optimalni rešitvi. Sicer pa bi bilo za razmisliti o spremembi načina generiranja funkcij - morda bi bilo smiselno najprej izbrati vrh znotraj intervala (ali pa v bližini - morda lahko uporabita kar normalno porazdelitev), nato pa izbereta še razdaljo od vrha do vznožij (tukaj bi morda bilo smiselno uporabiti kvadrat normalne porazdelitve).

Mimogrede, za normalno porazdelitev lahko uporabita kar R-jevo funkcijo `rnorm`. Dostop do R-jevih funkcij je mogoč preko objekta `r`, ker pa že imata spremenljivko s tem imenom, bo najbolje, če si ga uvozita v drugo spremenljivko, npr. `R`:
```python
from sage.interfaces.r import r as R
R.rnorm(1).sage() # vrne eno naključno vrednost po standardni normalni porazdelitvi in jo pretvori v Sageovo/Pythonovo število
```

**Comment by nezakrzan** [comment]
Hvala za vso pomoč.
